### ISSUE TITLE
workshop pages 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/dataWebsite#32]
test page is at: 
https://bulib.github.io/dataWebsite/workshops/2016/12/11/test-workshop.html

there can be linking issues depending on the website build

**Comment by tomhohenstein** [comment]
https://bulib.github.io/dataWebsite/workshops/2016/09/15/Writing-a-dmp.html

**Comment by liapark** [comment]
Adjustment of center alignment (of the workshop boxes) need to be made according to the title at the top and the overall size of the page. Left section of boxes are slightly larger than the ones on the right, and gap between the two sections are not in the center (alignment problem stated before). 

The dimension of the box on the right is the same with that of the left, but the actual box is smaller because the dimension of the right includes the gap dimensions.

**Comment by liapark** [comment]
Also, the order of the patterns, if it goes from purple, dark red, red, yellow, light green, dark green then blue, would be most ideal!

**Comment by tomhohenstein** [comment]
new layout drafted and live in the demo site - still work to do but a good start

**Comment by tomhohenstein** [comment]
need to add form functionality to workshops
