### ISSUE TITLE
Mobile Layout Revision

### ISSUE THREAD

**Issue by liapark** [bulib/dataWebsite#61]
Some revisions are needed for mobile layouts! Will add more revisions as I finish them.
[Mobile Home Page Revisions.pdf](https://github.com/bulib/dataWebsite/files/805194/Mobile.Home.Page.Revisions.pdf)
[Mobile Manage Revisions.pdf](https://github.com/bulib/dataWebsite/files/805195/Mobile.Manage.Revisions.pdf)

DONE - @tomhohenstein

**Comment by liapark** [comment]
[Mobile Manage B Revisions.pdf](https://github.com/bulib/dataWebsite/files/805220/Mobile.Manage.B.Revisions.pdf)

DONE - @tomhohenstein

**Comment by liapark** [comment]
[Mobile Workshop Revisions.pdf](https://github.com/bulib/dataWebsite/files/805236/Mobile.Workshop.Revisions.pdf)

Regarding the workshop page, the border definitely has to be fixed, but with the large amount of text, we should do consider on making them interactive like tools page. Would it be possible to have a look at it after the border issue is fixed?

-DONE @tomhohenstein

**Comment by mbcheng** [comment]
Things I've noticed when testing on mobile:
+ ~~Inconsistent footers. Footer for iPad includes Boston University Data Services + phone + email, but footer for iPhone and smaller devices include only phone + email.~~
+ ~~On Guides page, do you want text left-centered or centered? Text centered might be nicer to read especially on mobile~~ 
+ On Guides page, put periods at the end of all blurb sentences, but don't put a period at end of "Here you'll find all of our guides." @mbcheng a good to-do for your next work session
+ ~~On iPad version of home page, "consultations", "guides", "workshops" boxes look too stretched out. Text being left-centered looks odd on the iPad dimensions.~~ agreed - something for the summer
+ ~~In Citing Data, possibly add more white space between~~
+ ~~Video on Using DMPTool is not mobile-responsive. Under Select a Template, text is smaller than rest of text on the page. Make it same size as the rest of the test. Currently too small.~~
+ ~~On most of the mobile versions (besides iPad), content is not evenly distributed, everything looks shifted too left with excessive white space on the right. Might be due to video.~~ Agreed but I'm unlikely to get to this until the summer
+ ~~First bullet list under Adding Metadata looks very long. Might want to edit bullet points (can do that for you).~~
+ ~~Might want to add images to Adding Metadata Page, very text-heavy with bullet lists.~~
+ ~~In Writing NSF Data Management, title (white text) not properly centered on background image.~~
+ ~~Mobile versions of Writing NSF Data Management have excessive white space on the right as well. Seen a little bit on Galaxy S5 and iPhone 6. Very noticeable on iPhone 5.~~ summer task - good catch
+ ~~In Selecting A Data Repository, title (white text) not properly centered on background image.~~
+ In Selecting a Data Repository, inconsistent lists, some have – while others start with : @mbcheng a good to-do for your next session
+ ~~Selecting a Data Repository is another very text-heavy page.~~
+  ~~In Writing a Data Management Plan, title (white text) not properly centered on background image.~~
+ ~~Mobile versions of Writing a DMP have excessive white space on the right. Seen a little bit on Galaxy S5 and iPhone 6. Very noticeable on iPhone 5.~~
+ ~~Writing a DMP - text-heavy page.~~
+ ~~On calendar, each blurb about the event looks excessively too long on mobile/ content might be too narrow – possibly widen the width of the content.~~ 
+ ~~In Writing NSF Data Management, for part "Be mindful that NSF directorates and divisions may have more specific requirements" I would keep that either bold and no block-quote or have block-quote but don't make the text bold. I wouldn't apply both of those elements though.~~
+ ~~Background image on home page can't really be seen on mobile versions (except on iPad).~~
+ ~~On home page, I like that you can click inside the box and the gray border turns to green. Keep that consistent. When you click inside the box for on-campus partners, the gray borders do not turn green.~~ done!

**Comment by tomhohenstein** [comment]
@mbcheng great catches and suggestions. I know some of the pages are text heavy but at this point I think we have to go with them as they are (for better or worse). I lined through your notes that I believe Julia is working on or that I don't know if we can resolve at this point. 

I also added @mbcheng to the suggestions that you can work on during your next shift. 

The rest are things I'll be working on (and striking through when they are done). 

Great work!

**Comment by tomhohenstein** [comment]
closing this as the issues have been addressed. we can reopen it if I missed anything
